// Mocks generated by Mockito 5.0.16 from annotations
// in untitled3/test/Screens/Main_test.dart.
// Do not manually edit this file.

import 'dart:ui' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:untitled3/generated/i18n.dart' as _i3;
import 'package:untitled3/Observables/ScreenNavigator.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [MainNavObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockMainNavObserver extends _i1.Mock implements _i2.MainNavObserver {
  MockMainNavObserver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set currentScreen(dynamic _currentScreen) =>
      super.noSuchMethod(Invocation.setter(#currentScreen, _currentScreen),
          returnValueForMissingStub: null);
  @override
  String get screenTitle =>
      (super.noSuchMethod(Invocation.getter(#screenTitle), returnValue: '')
          as String);
  @override
  set screenTitle(String? _screenTitle) =>
      super.noSuchMethod(Invocation.setter(#screenTitle, _screenTitle),
          returnValueForMissingStub: null);
  @override
  set focusedNavBtn(dynamic _focusedNavBtn) =>
      super.noSuchMethod(Invocation.setter(#focusedNavBtn, _focusedNavBtn),
          returnValueForMissingStub: null);
  @override
  void changeScreen(dynamic screen) =>
      super.noSuchMethod(Invocation.method(#changeScreen, [screen]),
          returnValueForMissingStub: null);
  @override
  void setTitle(String? title) =>
      super.noSuchMethod(Invocation.method(#setTitle, [title]),
          returnValueForMissingStub: null);
  @override
  void setFocusedBtn(dynamic focusedBtn) =>
      super.noSuchMethod(Invocation.method(#setFocusedBtn, [focusedBtn]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [I18n].
///
/// See the documentation for Mockito's code generation for more information.
class MockI18n extends _i1.Mock implements _i3.I18n {
  MockI18n() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TextDirection get textDirection =>
      (super.noSuchMethod(Invocation.getter(#textDirection),
          returnValue: _i4.TextDirection.rtl) as _i4.TextDirection);
  @override
  String get homeScreenName =>
      (super.noSuchMethod(Invocation.getter(#homeScreenName), returnValue: '')
          as String);
  @override
  String get menuScreenName =>
      (super.noSuchMethod(Invocation.getter(#menuScreenName), returnValue: '')
          as String);
  @override
  String get notesScreenName =>
      (super.noSuchMethod(Invocation.getter(#notesScreenName), returnValue: '')
          as String);
  @override
  String get notificationsScreenName =>
      (super.noSuchMethod(Invocation.getter(#notificationsScreenName),
          returnValue: '') as String);
  @override
  String get settingScreenName => (super
          .noSuchMethod(Invocation.getter(#settingScreenName), returnValue: '')
      as String);
  @override
  String get calendarScreenName => (super
          .noSuchMethod(Invocation.getter(#calendarScreenName), returnValue: '')
      as String);
  @override
  String get micButton =>
      (super.noSuchMethod(Invocation.getter(#micButton), returnValue: '')
          as String);
  @override
  String get pressToRecord =>
      (super.noSuchMethod(Invocation.getter(#pressToRecord), returnValue: '')
          as String);
  @override
  String get yes =>
      (super.noSuchMethod(Invocation.getter(#yes), returnValue: '') as String);
  @override
  String get saveNote =>
      (super.noSuchMethod(Invocation.getter(#saveNote), returnValue: '')
          as String);
  @override
  String get date =>
      (super.noSuchMethod(Invocation.getter(#date), returnValue: '') as String);
  @override
  String get note =>
      (super.noSuchMethod(Invocation.getter(#note), returnValue: '') as String);
  @override
  String get notesDetailScreenName =>
      (super.noSuchMethod(Invocation.getter(#notesDetailScreenName),
          returnValue: '') as String);
  @override
  String get addNotesScreenName => (super
          .noSuchMethod(Invocation.getter(#addNotesScreenName), returnValue: '')
      as String);
  @override
  String get checklistScreenName =>
      (super.noSuchMethod(Invocation.getter(#checklistScreenName),
          returnValue: '') as String);
  @override
  String get help =>
      (super.noSuchMethod(Invocation.getter(#help), returnValue: '') as String);
  @override
  String get trigger =>
      (super.noSuchMethod(Invocation.getter(#trigger), returnValue: '')
          as String);
  @override
  String get syncToCloudScreen => (super
          .noSuchMethod(Invocation.getter(#syncToCloudScreen), returnValue: '')
      as String);
  @override
  String get generalSettingsScreen =>
      (super.noSuchMethod(Invocation.getter(#generalSettingsScreen),
          returnValue: '') as String);
  @override
  String get onboardCloudSetup => (super
          .noSuchMethod(Invocation.getter(#onboardCloudSetup), returnValue: '')
      as String);
  @override
  String get onboardPermissionSetup =>
      (super.noSuchMethod(Invocation.getter(#onboardPermissionSetup),
          returnValue: '') as String);
  @override
  String get onboardLangSetup =>
      (super.noSuchMethod(Invocation.getter(#onboardLangSetup), returnValue: '')
          as String);
  @override
  String get walkthroughScreen => (super
          .noSuchMethod(Invocation.getter(#walkthroughScreen), returnValue: '')
      as String);
  @override
  String get cloudSetupPrompt =>
      (super.noSuchMethod(Invocation.getter(#cloudSetupPrompt), returnValue: '')
          as String);
  @override
  String get no =>
      (super.noSuchMethod(Invocation.getter(#no), returnValue: '') as String);
  @override
  String get welcome =>
      (super.noSuchMethod(Invocation.getter(#welcome), returnValue: '')
          as String);
  @override
  String get back =>
      (super.noSuchMethod(Invocation.getter(#back), returnValue: '') as String);
  @override
  String get next =>
      (super.noSuchMethod(Invocation.getter(#next), returnValue: '') as String);
  @override
  String get selectLanguage =>
      (super.noSuchMethod(Invocation.getter(#selectLanguage), returnValue: '')
          as String);
  @override
  String get language =>
      (super.noSuchMethod(Invocation.getter(#language), returnValue: '')
          as String);
  @override
  String get promptPermission =>
      (super.noSuchMethod(Invocation.getter(#promptPermission), returnValue: '')
          as String);
  @override
  String get promptTheme =>
      (super.noSuchMethod(Invocation.getter(#promptTheme), returnValue: '')
          as String);
  @override
  String get promptNoteFontSize => (super
          .noSuchMethod(Invocation.getter(#promptNoteFontSize), returnValue: '')
      as String);
  @override
  String get promptMenuFontSize => (super
          .noSuchMethod(Invocation.getter(#promptMenuFontSize), returnValue: '')
      as String);
  @override
  String get promptNoteDeletionTimeline =>
      (super.noSuchMethod(Invocation.getter(#promptNoteDeletionTimeline),
          returnValue: '') as String);
  @override
  String get small =>
      (super.noSuchMethod(Invocation.getter(#small), returnValue: '')
          as String);
  @override
  String get medium =>
      (super.noSuchMethod(Invocation.getter(#medium), returnValue: '')
          as String);
  @override
  String get large =>
      (super.noSuchMethod(Invocation.getter(#large), returnValue: '')
          as String);
  @override
  String get cancel =>
      (super.noSuchMethod(Invocation.getter(#cancel), returnValue: '')
          as String);
  @override
  String get save =>
      (super.noSuchMethod(Invocation.getter(#save), returnValue: '') as String);
  @override
  String get securitySettings =>
      (super.noSuchMethod(Invocation.getter(#securitySettings), returnValue: '')
          as String);
  @override
  String get resetSettings =>
      (super.noSuchMethod(Invocation.getter(#resetSettings), returnValue: '')
          as String);
  @override
  String get permissionNote =>
      (super.noSuchMethod(Invocation.getter(#permissionNote), returnValue: '')
          as String);
  @override
  String get daysToKeepNotes =>
      (super.noSuchMethod(Invocation.getter(#daysToKeepNotes), returnValue: '')
          as String);
  @override
  String get noteFontSize =>
      (super.noSuchMethod(Invocation.getter(#noteFontSize), returnValue: '')
          as String);
  @override
  String get menuFontSize =>
      (super.noSuchMethod(Invocation.getter(#menuFontSize), returnValue: '')
          as String);
  @override
  String get syncToCloud =>
      (super.noSuchMethod(Invocation.getter(#syncToCloud), returnValue: '')
          as String);
  @override
  String get generalSetting =>
      (super.noSuchMethod(Invocation.getter(#generalSetting), returnValue: '')
          as String);
  @override
  String get loading =>
      (super.noSuchMethod(Invocation.getter(#loading), returnValue: '')
          as String);
  @override
  String get editNote =>
      (super.noSuchMethod(Invocation.getter(#editNote), returnValue: '')
          as String);
  @override
  String get deleteNote =>
      (super.noSuchMethod(Invocation.getter(#deleteNote), returnValue: '')
          as String);
  @override
  String get confirmNoteDeletion =>
      (super.noSuchMethod(Invocation.getter(#confirmNoteDeletion),
          returnValue: '') as String);
  @override
  String get areYouSureYouWantToDelete =>
      (super.noSuchMethod(Invocation.getter(#areYouSureYouWantToDelete),
          returnValue: '') as String);
  @override
  String get noteSaved =>
      (super.noSuchMethod(Invocation.getter(#noteSaved), returnValue: '')
          as String);
  @override
  String get enterNoteText =>
      (super.noSuchMethod(Invocation.getter(#enterNoteText), returnValue: '')
          as String);
  @override
  String get ok =>
      (super.noSuchMethod(Invocation.getter(#ok), returnValue: '') as String);
  @override
  String get noteSavedSuccess =>
      (super.noSuchMethod(Invocation.getter(#noteSavedSuccess), returnValue: '')
          as String);
  @override
  String get addNote =>
      (super.noSuchMethod(Invocation.getter(#addNote), returnValue: '')
          as String);
  @override
  String get speakOrWritePrompt => (super
          .noSuchMethod(Invocation.getter(#speakOrWritePrompt), returnValue: '')
      as String);
  @override
  String get theme =>
      (super.noSuchMethod(Invocation.getter(#theme), returnValue: '')
          as String);
  @override
  String get blue =>
      (super.noSuchMethod(Invocation.getter(#blue), returnValue: '') as String);
  @override
  String get pink =>
      (super.noSuchMethod(Invocation.getter(#pink), returnValue: '') as String);
  @override
  String get howCanIHelpYou =>
      (super.noSuchMethod(Invocation.getter(#howCanIHelpYou), returnValue: '')
          as String);
  @override
  String get turnOnNotesNotification =>
      (super.noSuchMethod(Invocation.getter(#turnOnNotesNotification),
          returnValue: '') as String);
  @override
  String get turnOnEventReminder =>
      (super.noSuchMethod(Invocation.getter(#turnOnEventReminder),
          returnValue: '') as String);
  @override
  String get reminderStartTime => (super
          .noSuchMethod(Invocation.getter(#reminderStartTime), returnValue: '')
      as String);
  @override
  String get activitiesNotifications =>
      (super.noSuchMethod(Invocation.getter(#activitiesNotifications),
          returnValue: '') as String);
  @override
  String get notesNotificiations =>
      (super.noSuchMethod(Invocation.getter(#notesNotificiations),
          returnValue: '') as String);
  @override
  String get turnOnHourlyWalkNotification =>
      (super.noSuchMethod(Invocation.getter(#turnOnHourlyWalkNotification),
          returnValue: '') as String);
  @override
  String get turnOnHourlyWaterNotification =>
      (super.noSuchMethod(Invocation.getter(#turnOnHourlyWaterNotification),
          returnValue: '') as String);
  @override
  String get turnOnBathroomNotification =>
      (super.noSuchMethod(Invocation.getter(#turnOnBathroomNotification),
          returnValue: '') as String);
  @override
  String get walkthroughVideoLine =>
      (super.noSuchMethod(Invocation.getter(#walkthroughVideoLine),
          returnValue: '') as String);
  @override
  String get micLimitedAccess =>
      (super.noSuchMethod(Invocation.getter(#micLimitedAccess), returnValue: '')
          as String);
  @override
  String get shouldICreateANote => (super
          .noSuchMethod(Invocation.getter(#shouldICreateANote), returnValue: '')
      as String);
  @override
  String get willNotCreateNote => (super
          .noSuchMethod(Invocation.getter(#willNotCreateNote), returnValue: '')
      as String);
  @override
  String get sureHowCanIHelp =>
      (super.noSuchMethod(Invocation.getter(#sureHowCanIHelp), returnValue: '')
          as String);
  @override
  String get thxBye =>
      (super.noSuchMethod(Invocation.getter(#thxBye), returnValue: '')
          as String);
  @override
  String get createdTheFollowingNote =>
      (super.noSuchMethod(Invocation.getter(#createdTheFollowingNote),
          returnValue: '') as String);
  @override
  String get startDate =>
      (super.noSuchMethod(Invocation.getter(#startDate), returnValue: '')
          as String);
  @override
  String get selectDate =>
      (super.noSuchMethod(Invocation.getter(#selectDate), returnValue: '')
          as String);
  @override
  String get enterTime =>
      (super.noSuchMethod(Invocation.getter(#enterTime), returnValue: '')
          as String);
  @override
  String get clearSelection =>
      (super.noSuchMethod(Invocation.getter(#clearSelection), returnValue: '')
          as String);
  @override
  String get helpScreen =>
      (super.noSuchMethod(Invocation.getter(#helpScreen), returnValue: '')
          as String);
  @override
  String get triggerScreen =>
      (super.noSuchMethod(Invocation.getter(#triggerScreen), returnValue: '')
          as String);
  @override
  String toString() => super.toString();
}
